### ISSUE TITLE
Add letter indicating day of the week

### ISSUE THREAD

**Issue by pete-may** [zincplusplus/habit-tracker#40]
Wondering if we could have the option of including a letter in the header of that tracker table that indicated day of the week. 

Something like 

| T 23 | W 24 | T 25 | F 26 | S 27 | S 28 |
|--|--|--|--|--|--|
|  |  |  |  |  | 

This is so when I miss updating after a few days it's easier to backfill.

**Comment by jeanys** [comment]
I solved this with some css snippet:
```css
.habit-tracker__cell[data-date]::before {
  font-size: 10px;
  display: block;
}
.habit-tracker__cell--monday[data-date]::before {
  content: "Mon ";
}
.habit-tracker__cell--tuesday[data-date]::before {
  content: "Tue ";
}
.habit-tracker__cell--wednesday[data-date]::before {
  content: "Wed ";
}
.habit-tracker__cell--thursday[data-date]::before {
  content: "Thu ";
}
.habit-tracker__cell--friday[data-date]::before {
  content: "Fri ";
}
.habit-tracker__cell--saturday[data-date]::before {
  content: "Sat ";
}
.habit-tracker__cell--sunday[data-date]::before {
  content: "Sun ";
}
```
